#: import RV components.components.RV
#: include components/components.kv

<ListScreen>:
    name: 'list_content_scr'
    MDBoxLayout:
        orientation: 'vertical'
        padding: dp(20), 0, dp(20), 0

        Widget:
            size_hint_y: None
            height: root.top_bar_height + root.top_bar_height * .25
            minimum_size: self.size

        RV:
            viewclass: 'ProdItemWithImg'
            id: rv_list_content